{% set version = '0.8.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggfittext
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggfittext_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggfittext/ggfittext_{{ version }}.tar.gz
  sha256: 88d7f01171f1f5cee0e1364619f6ef8f06d5ac891b51843c21201c4b1eaacb4c

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=2.2.1
    - r-shades >=1.3.1
    - r-stringi >=1.1.2
  run:
    - r-base
    - r-ggplot2 >=2.2.1
    - r-shades >=1.3.1
    - r-stringi >=1.1.2

test:
  commands:
    - $R -e "library('ggfittext')"           # [not win]
    - "\"%R%\" -e \"library('ggfittext')\""  # [win]

about:
  home: https://github.com/wilkox/ggfittext
  license: GPL-2
  summary: Provides 'ggplot2' geoms to fit text into a box by growing, shrinking or wrapping
    the text.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggfittext
# Title: Fit Text Inside a Box in 'ggplot2'
# Version: 0.8.0
# Authors@R: person("David", "Wilkins", email = "david@wilkox.org", role = c("aut", "cre"))
# Description: Provides 'ggplot2' geoms to fit text into a box by growing, shrinking or wrapping the text.
# Depends: R (>= 3.2.3)
# License: GPL-2
# LazyData: true
# Imports: grid (>= 3.1), stringi (>= 1.1.2), ggplot2 (>= 2.2.1), shades (>= 1.3.1)
# RoxygenNote: 6.1.1
# URL: https://github.com/wilkox/ggfittext
# BugReports: https://github.com/wilkox/ggfittext/issues
# Suggests: knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-06-23 21:51:30 UTC; wilkox
# Author: David Wilkins [aut, cre]
# Maintainer: David Wilkins <david@wilkox.org>
# Repository: CRAN
# Date/Publication: 2019-06-23 22:20:04 UTC
